/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkRouteImport } from './routes/work'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkIndexRouteImport } from './routes/work/index'
import { Route as FinanceIndexRouteImport } from './routes/finance/index'
import { Route as WorkSettingsRouteImport } from './routes/work/settings'
import { Route as WorkReportsRouteImport } from './routes/work/reports'
import { Route as WorkPayrollsRouteImport } from './routes/work/payrolls'
import { Route as WorkOpsRouteImport } from './routes/work/ops'
import { Route as FinanceTransactionsRouteImport } from './routes/finance/transactions'
import { Route as FinanceSettingsRouteImport } from './routes/finance/settings'
import { Route as FinanceCategoriesRouteImport } from './routes/finance/categories'
import { Route as ApiExportCsvRouteImport } from './routes/api/export-csv'

const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkIndexRoute = WorkIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkRoute,
} as any)
const FinanceIndexRoute = FinanceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FinanceRoute,
} as any)
const WorkSettingsRoute = WorkSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => WorkRoute,
} as any)
const WorkReportsRoute = WorkReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => WorkRoute,
} as any)
const WorkPayrollsRoute = WorkPayrollsRouteImport.update({
  id: '/payrolls',
  path: '/payrolls',
  getParentRoute: () => WorkRoute,
} as any)
const WorkOpsRoute = WorkOpsRouteImport.update({
  id: '/ops',
  path: '/ops',
  getParentRoute: () => WorkRoute,
} as any)
const FinanceTransactionsRoute = FinanceTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => FinanceRoute,
} as any)
const FinanceSettingsRoute = FinanceSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => FinanceRoute,
} as any)
const FinanceCategoriesRoute = FinanceCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => FinanceRoute,
} as any)
const ApiExportCsvRoute = ApiExportCsvRouteImport.update({
  id: '/api/export-csv',
  path: '/api/export-csv',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/finance': typeof FinanceRouteWithChildren
  '/work': typeof WorkRouteWithChildren
  '/api/export-csv': typeof ApiExportCsvRoute
  '/finance/categories': typeof FinanceCategoriesRoute
  '/finance/settings': typeof FinanceSettingsRoute
  '/finance/transactions': typeof FinanceTransactionsRoute
  '/work/ops': typeof WorkOpsRoute
  '/work/payrolls': typeof WorkPayrollsRoute
  '/work/reports': typeof WorkReportsRoute
  '/work/settings': typeof WorkSettingsRoute
  '/finance/': typeof FinanceIndexRoute
  '/work/': typeof WorkIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/export-csv': typeof ApiExportCsvRoute
  '/finance/categories': typeof FinanceCategoriesRoute
  '/finance/settings': typeof FinanceSettingsRoute
  '/finance/transactions': typeof FinanceTransactionsRoute
  '/work/ops': typeof WorkOpsRoute
  '/work/payrolls': typeof WorkPayrollsRoute
  '/work/reports': typeof WorkReportsRoute
  '/work/settings': typeof WorkSettingsRoute
  '/finance': typeof FinanceIndexRoute
  '/work': typeof WorkIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/finance': typeof FinanceRouteWithChildren
  '/work': typeof WorkRouteWithChildren
  '/api/export-csv': typeof ApiExportCsvRoute
  '/finance/categories': typeof FinanceCategoriesRoute
  '/finance/settings': typeof FinanceSettingsRoute
  '/finance/transactions': typeof FinanceTransactionsRoute
  '/work/ops': typeof WorkOpsRoute
  '/work/payrolls': typeof WorkPayrollsRoute
  '/work/reports': typeof WorkReportsRoute
  '/work/settings': typeof WorkSettingsRoute
  '/finance/': typeof FinanceIndexRoute
  '/work/': typeof WorkIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/finance'
    | '/work'
    | '/api/export-csv'
    | '/finance/categories'
    | '/finance/settings'
    | '/finance/transactions'
    | '/work/ops'
    | '/work/payrolls'
    | '/work/reports'
    | '/work/settings'
    | '/finance/'
    | '/work/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/export-csv'
    | '/finance/categories'
    | '/finance/settings'
    | '/finance/transactions'
    | '/work/ops'
    | '/work/payrolls'
    | '/work/reports'
    | '/work/settings'
    | '/finance'
    | '/work'
  id:
    | '__root__'
    | '/'
    | '/finance'
    | '/work'
    | '/api/export-csv'
    | '/finance/categories'
    | '/finance/settings'
    | '/finance/transactions'
    | '/work/ops'
    | '/work/payrolls'
    | '/work/reports'
    | '/work/settings'
    | '/finance/'
    | '/work/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FinanceRoute: typeof FinanceRouteWithChildren
  WorkRoute: typeof WorkRouteWithChildren
  ApiExportCsvRoute: typeof ApiExportCsvRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/': {
      id: '/work/'
      path: '/'
      fullPath: '/work/'
      preLoaderRoute: typeof WorkIndexRouteImport
      parentRoute: typeof WorkRoute
    }
    '/finance/': {
      id: '/finance/'
      path: '/'
      fullPath: '/finance/'
      preLoaderRoute: typeof FinanceIndexRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/work/settings': {
      id: '/work/settings'
      path: '/settings'
      fullPath: '/work/settings'
      preLoaderRoute: typeof WorkSettingsRouteImport
      parentRoute: typeof WorkRoute
    }
    '/work/reports': {
      id: '/work/reports'
      path: '/reports'
      fullPath: '/work/reports'
      preLoaderRoute: typeof WorkReportsRouteImport
      parentRoute: typeof WorkRoute
    }
    '/work/payrolls': {
      id: '/work/payrolls'
      path: '/payrolls'
      fullPath: '/work/payrolls'
      preLoaderRoute: typeof WorkPayrollsRouteImport
      parentRoute: typeof WorkRoute
    }
    '/work/ops': {
      id: '/work/ops'
      path: '/ops'
      fullPath: '/work/ops'
      preLoaderRoute: typeof WorkOpsRouteImport
      parentRoute: typeof WorkRoute
    }
    '/finance/transactions': {
      id: '/finance/transactions'
      path: '/transactions'
      fullPath: '/finance/transactions'
      preLoaderRoute: typeof FinanceTransactionsRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/finance/settings': {
      id: '/finance/settings'
      path: '/settings'
      fullPath: '/finance/settings'
      preLoaderRoute: typeof FinanceSettingsRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/finance/categories': {
      id: '/finance/categories'
      path: '/categories'
      fullPath: '/finance/categories'
      preLoaderRoute: typeof FinanceCategoriesRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/api/export-csv': {
      id: '/api/export-csv'
      path: '/api/export-csv'
      fullPath: '/api/export-csv'
      preLoaderRoute: typeof ApiExportCsvRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface FinanceRouteChildren {
  FinanceCategoriesRoute: typeof FinanceCategoriesRoute
  FinanceSettingsRoute: typeof FinanceSettingsRoute
  FinanceTransactionsRoute: typeof FinanceTransactionsRoute
  FinanceIndexRoute: typeof FinanceIndexRoute
}

const FinanceRouteChildren: FinanceRouteChildren = {
  FinanceCategoriesRoute: FinanceCategoriesRoute,
  FinanceSettingsRoute: FinanceSettingsRoute,
  FinanceTransactionsRoute: FinanceTransactionsRoute,
  FinanceIndexRoute: FinanceIndexRoute,
}

const FinanceRouteWithChildren =
  FinanceRoute._addFileChildren(FinanceRouteChildren)

interface WorkRouteChildren {
  WorkOpsRoute: typeof WorkOpsRoute
  WorkPayrollsRoute: typeof WorkPayrollsRoute
  WorkReportsRoute: typeof WorkReportsRoute
  WorkSettingsRoute: typeof WorkSettingsRoute
  WorkIndexRoute: typeof WorkIndexRoute
}

const WorkRouteChildren: WorkRouteChildren = {
  WorkOpsRoute: WorkOpsRoute,
  WorkPayrollsRoute: WorkPayrollsRoute,
  WorkReportsRoute: WorkReportsRoute,
  WorkSettingsRoute: WorkSettingsRoute,
  WorkIndexRoute: WorkIndexRoute,
}

const WorkRouteWithChildren = WorkRoute._addFileChildren(WorkRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FinanceRoute: FinanceRouteWithChildren,
  WorkRoute: WorkRouteWithChildren,
  ApiExportCsvRoute: ApiExportCsvRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
