/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as ProtectedIndexRouteImport } from './routes/_protected/index'
import { Route as ApiExportCsvRouteImport } from './routes/api/export-csv'
import { Route as ProtectedWorkRouteImport } from './routes/_protected/work'
import { Route as ProtectedFinanceRouteImport } from './routes/_protected/finance'
import { Route as ProtectedWorkIndexRouteImport } from './routes/_protected/work/index'
import { Route as ProtectedFinanceIndexRouteImport } from './routes/_protected/finance/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ProtectedWorkSettingsRouteImport } from './routes/_protected/work/settings'
import { Route as ProtectedWorkReportsRouteImport } from './routes/_protected/work/reports'
import { Route as ProtectedWorkPayrollsRouteImport } from './routes/_protected/work/payrolls'
import { Route as ProtectedWorkOpsRouteImport } from './routes/_protected/work/ops'
import { Route as ProtectedFinanceTransactionsRouteImport } from './routes/_protected/finance/transactions'
import { Route as ProtectedFinanceSettingsRouteImport } from './routes/_protected/finance/settings'
import { Route as ProtectedFinanceGoalsRouteImport } from './routes/_protected/finance/goals'
import { Route as ProtectedFinanceCategoriesRouteImport } from './routes/_protected/finance/categories'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedIndexRoute = ProtectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ApiExportCsvRoute = ApiExportCsvRouteImport.update({
  id: '/api/export-csv',
  path: '/api/export-csv',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedWorkRoute = ProtectedWorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedFinanceRoute = ProtectedFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedWorkIndexRoute = ProtectedWorkIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedWorkRoute,
} as any)
const ProtectedFinanceIndexRoute = ProtectedFinanceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedFinanceRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedWorkSettingsRoute = ProtectedWorkSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ProtectedWorkRoute,
} as any)
const ProtectedWorkReportsRoute = ProtectedWorkReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => ProtectedWorkRoute,
} as any)
const ProtectedWorkPayrollsRoute = ProtectedWorkPayrollsRouteImport.update({
  id: '/payrolls',
  path: '/payrolls',
  getParentRoute: () => ProtectedWorkRoute,
} as any)
const ProtectedWorkOpsRoute = ProtectedWorkOpsRouteImport.update({
  id: '/ops',
  path: '/ops',
  getParentRoute: () => ProtectedWorkRoute,
} as any)
const ProtectedFinanceTransactionsRoute =
  ProtectedFinanceTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => ProtectedFinanceRoute,
  } as any)
const ProtectedFinanceSettingsRoute =
  ProtectedFinanceSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => ProtectedFinanceRoute,
  } as any)
const ProtectedFinanceGoalsRoute = ProtectedFinanceGoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => ProtectedFinanceRoute,
} as any)
const ProtectedFinanceCategoriesRoute =
  ProtectedFinanceCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => ProtectedFinanceRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ProtectedIndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/finance': typeof ProtectedFinanceRouteWithChildren
  '/work': typeof ProtectedWorkRouteWithChildren
  '/api/export-csv': typeof ApiExportCsvRoute
  '/finance/categories': typeof ProtectedFinanceCategoriesRoute
  '/finance/goals': typeof ProtectedFinanceGoalsRoute
  '/finance/settings': typeof ProtectedFinanceSettingsRoute
  '/finance/transactions': typeof ProtectedFinanceTransactionsRoute
  '/work/ops': typeof ProtectedWorkOpsRoute
  '/work/payrolls': typeof ProtectedWorkPayrollsRoute
  '/work/reports': typeof ProtectedWorkReportsRoute
  '/work/settings': typeof ProtectedWorkSettingsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/finance/': typeof ProtectedFinanceIndexRoute
  '/work/': typeof ProtectedWorkIndexRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/api/export-csv': typeof ApiExportCsvRoute
  '/': typeof ProtectedIndexRoute
  '/finance/categories': typeof ProtectedFinanceCategoriesRoute
  '/finance/goals': typeof ProtectedFinanceGoalsRoute
  '/finance/settings': typeof ProtectedFinanceSettingsRoute
  '/finance/transactions': typeof ProtectedFinanceTransactionsRoute
  '/work/ops': typeof ProtectedWorkOpsRoute
  '/work/payrolls': typeof ProtectedWorkPayrollsRoute
  '/work/reports': typeof ProtectedWorkReportsRoute
  '/work/settings': typeof ProtectedWorkSettingsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/finance': typeof ProtectedFinanceIndexRoute
  '/work': typeof ProtectedWorkIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_protected/finance': typeof ProtectedFinanceRouteWithChildren
  '/_protected/work': typeof ProtectedWorkRouteWithChildren
  '/api/export-csv': typeof ApiExportCsvRoute
  '/_protected/': typeof ProtectedIndexRoute
  '/_protected/finance/categories': typeof ProtectedFinanceCategoriesRoute
  '/_protected/finance/goals': typeof ProtectedFinanceGoalsRoute
  '/_protected/finance/settings': typeof ProtectedFinanceSettingsRoute
  '/_protected/finance/transactions': typeof ProtectedFinanceTransactionsRoute
  '/_protected/work/ops': typeof ProtectedWorkOpsRoute
  '/_protected/work/payrolls': typeof ProtectedWorkPayrollsRoute
  '/_protected/work/reports': typeof ProtectedWorkReportsRoute
  '/_protected/work/settings': typeof ProtectedWorkSettingsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_protected/finance/': typeof ProtectedFinanceIndexRoute
  '/_protected/work/': typeof ProtectedWorkIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/finance'
    | '/work'
    | '/api/export-csv'
    | '/finance/categories'
    | '/finance/goals'
    | '/finance/settings'
    | '/finance/transactions'
    | '/work/ops'
    | '/work/payrolls'
    | '/work/reports'
    | '/work/settings'
    | '/api/auth/$'
    | '/finance/'
    | '/work/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/api/export-csv'
    | '/'
    | '/finance/categories'
    | '/finance/goals'
    | '/finance/settings'
    | '/finance/transactions'
    | '/work/ops'
    | '/work/payrolls'
    | '/work/reports'
    | '/work/settings'
    | '/api/auth/$'
    | '/finance'
    | '/work'
  id:
    | '__root__'
    | '/_protected'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/_protected/finance'
    | '/_protected/work'
    | '/api/export-csv'
    | '/_protected/'
    | '/_protected/finance/categories'
    | '/_protected/finance/goals'
    | '/_protected/finance/settings'
    | '/_protected/finance/transactions'
    | '/_protected/work/ops'
    | '/_protected/work/payrolls'
    | '/_protected/work/reports'
    | '/_protected/work/settings'
    | '/api/auth/$'
    | '/_protected/finance/'
    | '/_protected/work/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRoute: typeof ProtectedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiExportCsvRoute: typeof ApiExportCsvRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/': {
      id: '/_protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/api/export-csv': {
      id: '/api/export-csv'
      path: '/api/export-csv'
      fullPath: '/api/export-csv'
      preLoaderRoute: typeof ApiExportCsvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/work': {
      id: '/_protected/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof ProtectedWorkRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/finance': {
      id: '/_protected/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof ProtectedFinanceRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/work/': {
      id: '/_protected/work/'
      path: '/'
      fullPath: '/work/'
      preLoaderRoute: typeof ProtectedWorkIndexRouteImport
      parentRoute: typeof ProtectedWorkRoute
    }
    '/_protected/finance/': {
      id: '/_protected/finance/'
      path: '/'
      fullPath: '/finance/'
      preLoaderRoute: typeof ProtectedFinanceIndexRouteImport
      parentRoute: typeof ProtectedFinanceRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/work/settings': {
      id: '/_protected/work/settings'
      path: '/settings'
      fullPath: '/work/settings'
      preLoaderRoute: typeof ProtectedWorkSettingsRouteImport
      parentRoute: typeof ProtectedWorkRoute
    }
    '/_protected/work/reports': {
      id: '/_protected/work/reports'
      path: '/reports'
      fullPath: '/work/reports'
      preLoaderRoute: typeof ProtectedWorkReportsRouteImport
      parentRoute: typeof ProtectedWorkRoute
    }
    '/_protected/work/payrolls': {
      id: '/_protected/work/payrolls'
      path: '/payrolls'
      fullPath: '/work/payrolls'
      preLoaderRoute: typeof ProtectedWorkPayrollsRouteImport
      parentRoute: typeof ProtectedWorkRoute
    }
    '/_protected/work/ops': {
      id: '/_protected/work/ops'
      path: '/ops'
      fullPath: '/work/ops'
      preLoaderRoute: typeof ProtectedWorkOpsRouteImport
      parentRoute: typeof ProtectedWorkRoute
    }
    '/_protected/finance/transactions': {
      id: '/_protected/finance/transactions'
      path: '/transactions'
      fullPath: '/finance/transactions'
      preLoaderRoute: typeof ProtectedFinanceTransactionsRouteImport
      parentRoute: typeof ProtectedFinanceRoute
    }
    '/_protected/finance/settings': {
      id: '/_protected/finance/settings'
      path: '/settings'
      fullPath: '/finance/settings'
      preLoaderRoute: typeof ProtectedFinanceSettingsRouteImport
      parentRoute: typeof ProtectedFinanceRoute
    }
    '/_protected/finance/goals': {
      id: '/_protected/finance/goals'
      path: '/goals'
      fullPath: '/finance/goals'
      preLoaderRoute: typeof ProtectedFinanceGoalsRouteImport
      parentRoute: typeof ProtectedFinanceRoute
    }
    '/_protected/finance/categories': {
      id: '/_protected/finance/categories'
      path: '/categories'
      fullPath: '/finance/categories'
      preLoaderRoute: typeof ProtectedFinanceCategoriesRouteImport
      parentRoute: typeof ProtectedFinanceRoute
    }
  }
}

interface ProtectedFinanceRouteChildren {
  ProtectedFinanceCategoriesRoute: typeof ProtectedFinanceCategoriesRoute
  ProtectedFinanceGoalsRoute: typeof ProtectedFinanceGoalsRoute
  ProtectedFinanceSettingsRoute: typeof ProtectedFinanceSettingsRoute
  ProtectedFinanceTransactionsRoute: typeof ProtectedFinanceTransactionsRoute
  ProtectedFinanceIndexRoute: typeof ProtectedFinanceIndexRoute
}

const ProtectedFinanceRouteChildren: ProtectedFinanceRouteChildren = {
  ProtectedFinanceCategoriesRoute: ProtectedFinanceCategoriesRoute,
  ProtectedFinanceGoalsRoute: ProtectedFinanceGoalsRoute,
  ProtectedFinanceSettingsRoute: ProtectedFinanceSettingsRoute,
  ProtectedFinanceTransactionsRoute: ProtectedFinanceTransactionsRoute,
  ProtectedFinanceIndexRoute: ProtectedFinanceIndexRoute,
}

const ProtectedFinanceRouteWithChildren =
  ProtectedFinanceRoute._addFileChildren(ProtectedFinanceRouteChildren)

interface ProtectedWorkRouteChildren {
  ProtectedWorkOpsRoute: typeof ProtectedWorkOpsRoute
  ProtectedWorkPayrollsRoute: typeof ProtectedWorkPayrollsRoute
  ProtectedWorkReportsRoute: typeof ProtectedWorkReportsRoute
  ProtectedWorkSettingsRoute: typeof ProtectedWorkSettingsRoute
  ProtectedWorkIndexRoute: typeof ProtectedWorkIndexRoute
}

const ProtectedWorkRouteChildren: ProtectedWorkRouteChildren = {
  ProtectedWorkOpsRoute: ProtectedWorkOpsRoute,
  ProtectedWorkPayrollsRoute: ProtectedWorkPayrollsRoute,
  ProtectedWorkReportsRoute: ProtectedWorkReportsRoute,
  ProtectedWorkSettingsRoute: ProtectedWorkSettingsRoute,
  ProtectedWorkIndexRoute: ProtectedWorkIndexRoute,
}

const ProtectedWorkRouteWithChildren = ProtectedWorkRoute._addFileChildren(
  ProtectedWorkRouteChildren,
)

interface ProtectedRouteChildren {
  ProtectedFinanceRoute: typeof ProtectedFinanceRouteWithChildren
  ProtectedWorkRoute: typeof ProtectedWorkRouteWithChildren
  ProtectedIndexRoute: typeof ProtectedIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedFinanceRoute: ProtectedFinanceRouteWithChildren,
  ProtectedWorkRoute: ProtectedWorkRouteWithChildren,
  ProtectedIndexRoute: ProtectedIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRoute: ProtectedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiExportCsvRoute: ApiExportCsvRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
