/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FinanceIndexRouteImport } from './routes/finance/index'
import { Route as FinanceTransactionsRouteImport } from './routes/finance/transactions'
import { Route as FinanceSettingsRouteImport } from './routes/finance/settings'
import { Route as FinanceCategoriesRouteImport } from './routes/finance/categories'
import { Route as ApiExportCsvRouteImport } from './routes/api/export-csv'

const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceIndexRoute = FinanceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FinanceRoute,
} as any)
const FinanceTransactionsRoute = FinanceTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => FinanceRoute,
} as any)
const FinanceSettingsRoute = FinanceSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => FinanceRoute,
} as any)
const FinanceCategoriesRoute = FinanceCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => FinanceRoute,
} as any)
const ApiExportCsvRoute = ApiExportCsvRouteImport.update({
  id: '/api/export-csv',
  path: '/api/export-csv',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/finance': typeof FinanceRouteWithChildren
  '/api/export-csv': typeof ApiExportCsvRoute
  '/finance/categories': typeof FinanceCategoriesRoute
  '/finance/settings': typeof FinanceSettingsRoute
  '/finance/transactions': typeof FinanceTransactionsRoute
  '/finance/': typeof FinanceIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/export-csv': typeof ApiExportCsvRoute
  '/finance/categories': typeof FinanceCategoriesRoute
  '/finance/settings': typeof FinanceSettingsRoute
  '/finance/transactions': typeof FinanceTransactionsRoute
  '/finance': typeof FinanceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/finance': typeof FinanceRouteWithChildren
  '/api/export-csv': typeof ApiExportCsvRoute
  '/finance/categories': typeof FinanceCategoriesRoute
  '/finance/settings': typeof FinanceSettingsRoute
  '/finance/transactions': typeof FinanceTransactionsRoute
  '/finance/': typeof FinanceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/finance'
    | '/api/export-csv'
    | '/finance/categories'
    | '/finance/settings'
    | '/finance/transactions'
    | '/finance/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/export-csv'
    | '/finance/categories'
    | '/finance/settings'
    | '/finance/transactions'
    | '/finance'
  id:
    | '__root__'
    | '/'
    | '/finance'
    | '/api/export-csv'
    | '/finance/categories'
    | '/finance/settings'
    | '/finance/transactions'
    | '/finance/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FinanceRoute: typeof FinanceRouteWithChildren
  ApiExportCsvRoute: typeof ApiExportCsvRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/': {
      id: '/finance/'
      path: '/'
      fullPath: '/finance/'
      preLoaderRoute: typeof FinanceIndexRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/finance/transactions': {
      id: '/finance/transactions'
      path: '/transactions'
      fullPath: '/finance/transactions'
      preLoaderRoute: typeof FinanceTransactionsRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/finance/settings': {
      id: '/finance/settings'
      path: '/settings'
      fullPath: '/finance/settings'
      preLoaderRoute: typeof FinanceSettingsRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/finance/categories': {
      id: '/finance/categories'
      path: '/categories'
      fullPath: '/finance/categories'
      preLoaderRoute: typeof FinanceCategoriesRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/api/export-csv': {
      id: '/api/export-csv'
      path: '/api/export-csv'
      fullPath: '/api/export-csv'
      preLoaderRoute: typeof ApiExportCsvRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface FinanceRouteChildren {
  FinanceCategoriesRoute: typeof FinanceCategoriesRoute
  FinanceSettingsRoute: typeof FinanceSettingsRoute
  FinanceTransactionsRoute: typeof FinanceTransactionsRoute
  FinanceIndexRoute: typeof FinanceIndexRoute
}

const FinanceRouteChildren: FinanceRouteChildren = {
  FinanceCategoriesRoute: FinanceCategoriesRoute,
  FinanceSettingsRoute: FinanceSettingsRoute,
  FinanceTransactionsRoute: FinanceTransactionsRoute,
  FinanceIndexRoute: FinanceIndexRoute,
}

const FinanceRouteWithChildren =
  FinanceRoute._addFileChildren(FinanceRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FinanceRoute: FinanceRouteWithChildren,
  ApiExportCsvRoute: ApiExportCsvRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
